// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWqHc18szXOMbuxWn7E6WL67Xfls2pNlM',
    appId: '1:156800630605:web:8a13d9074b4c91a157c104',
    messagingSenderId: '156800630605',
    projectId: 'flutterfbsignin',
    authDomain: 'flutterfbsignin.firebaseapp.com',
    storageBucket: 'flutterfbsignin.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClcp_CZHKJwz7YjLTA5BfShDYnUg8lhYw',
    appId: '1:156800630605:android:9bdef17d0440ffa957c104',
    messagingSenderId: '156800630605',
    projectId: 'flutterfbsignin',
    storageBucket: 'flutterfbsignin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKf2rfME96kbAVoflRXiatVV-OFGPQNH8',
    appId: '1:156800630605:ios:c5e2d3c6547b876d57c104',
    messagingSenderId: '156800630605',
    projectId: 'flutterfbsignin',
    storageBucket: 'flutterfbsignin.appspot.com',
    androidClientId: '156800630605-l2bn5sb56qpov73hsp2thrvf2n0tap7l.apps.googleusercontent.com',
    iosClientId: '156800630605-rgtr7ajratfs5v63c90q5kj5rr4d4lr1.apps.googleusercontent.com',
    iosBundleId: 'com.example.signInFirebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKf2rfME96kbAVoflRXiatVV-OFGPQNH8',
    appId: '1:156800630605:ios:c5e2d3c6547b876d57c104',
    messagingSenderId: '156800630605',
    projectId: 'flutterfbsignin',
    storageBucket: 'flutterfbsignin.appspot.com',
    androidClientId: '156800630605-l2bn5sb56qpov73hsp2thrvf2n0tap7l.apps.googleusercontent.com',
    iosClientId: '156800630605-rgtr7ajratfs5v63c90q5kj5rr4d4lr1.apps.googleusercontent.com',
    iosBundleId: 'com.example.signInFirebaseAuth',
  );
}
